#include <pl_defs.h>
#include <samc21.h>


static inline void adc_init() {
  // Configure Pins
  PORTA.PMUX[1].reg   = PORT_PMUX_PMUXE(MUX_PA02B_ADC0_AIN0) | PORT_PMUX_PMUXO(MUX_PA03B_ADC0_AIN1);
  PORTA.PINCFG[2].reg = PORT_PINCFG_PMUXEN;
  PORTA.PINCFG[3].reg = PORT_PINCFG_PMUXEN;

  // Init ADC
  ADC0->INPUTCTRL.reg
    = ADC_INPUTCTRL_MUXNEG_GND | ADC_INPUTCTRL_MUXPOS_AIN0;
  ADC0->CALIB.reg
    = ADC_CALIB_BIASCOMP(*(uint32_t *) ADC0_FUSES_BIASCOMP_ADDR >> ADC0_FUSES_BIASCOMP_Pos)
    | ADC_CALIB_BIASREFBUF(*(uint32_t *) ADC0_FUSES_BIASREFBUF_ADDR >> ADC0_FUSES_BIASREFBUF_Pos);

  ADC0->CTRLB.reg   = ADC_CTRLB_PRESCALER_DIV2;
  ADC0->REFCTRL.reg = ADC_REFCTRL_REFSEL_INTVCC2; // VDDANA
  ADC0->CTRLC.reg   = ADC_CTRLC_RESSEL_8BIT;
  ADC0->EVCTRL.reg  = ADC_EVCTRL_STARTEI;
  ADC0->SEQCTRL.reg = ADC_SEQCTRL_SEQEN_AIN(0) | ADC_SEQCTRL_SEQEN_AIN(1);
  ADC0->CTRLA.reg   = ADC_CTRLA_ENABLE | ADC_CTRLA_RUNSTDBY | ADC_CTRLA_ONDEMAND;
}